### PR TITLE
Feat #17: Making Changes in UI

### LINKED ISSUE #17: feat: Making Changes in UI
Hey! I want to make some changes to the UI by using the library `particles.js`. That'll be looking too cool, and UI will look good.
Please assign this issue to me.

### PR DESCRIPTION
**Pull request by superiorsd10**
Resolves #17 
I've added the particles in the background using the `particle.js` library.

### CODE REVIEW

**Comment by Nainish-Rai** [comment]
@superiorsd10 have you changed the background position?

**Comment by Nainish-Rai** [comment]
@Nainish-Rai Background is slightly misplaced; I will fix that in morning and then this PR will be merged after the fix;
Also change img to this gif https://i.pinimg.com/originals/8c/46/c7/8c46c76c357be2dff2459d34313e6d2e.gif

**Comment by superiorsd10** [comment]
@Nainish-Rai Okay, Thank You :) I'll be changing that.

**Comment by superiorsd10** [comment]
@Nainish-Rai Is this fine?
I've also added a border to this GIF.
SCR-20221005-t1

**Pull request merged**
