### PR TITLE
Added aesthetic color Scheme

### PR DESCRIPTION
**Pull request by Sidd2024**
Screenshot (26)

### CODE REVIEW

**Comment by Nainish-Rai** [comment]
@Sidd2024 Similar theme is already there, Try to create a new unique color scheme

**Comment by Sidd2024** [comment]
Oh my bad😅, I'll choose unique colors  this time!

**Comment by Sidd2024** [comment]
Hey!, @Nainish-Rai I've updated PR, please review and then I will also upload the gif with a new pr.
Screenshot (28)

**Comment by Nainish-Rai** [comment]
@Sidd2024 This one looks good! Thanks for contributing; Merged

**Pull request merged**
