### PR TITLE
Made a hamburger menu to switch b/w themes  Issue: #39

### PR DESCRIPTION
**Pull request by yes-im-harsh**
Issue: #39 

1. Added Hamburger menu.
2. Switch b/w all the "main-themes". 
3. Clean code with comments, and built on a pre-existing template.

@Nainish-Rai

### CODE REVIEW

**Comment by yes-im-harsh** [comment]
> @yes-im-harsh I have updated hamburger style check it and use it for all main-themes and also don't comment out html flex

I have created an index.html folder in the root and theme(main-themes) is changing.
But If I use the html flex, then I have to use the flex-wrap.

With flex in html
image

Without flex
image

Do you still want me to uncomment flex from html?

**Comment by Nainish-Rai** [comment]
@yes-im-harsh 
without flex there is no margin from top
Screenshot from 2022-10-07 12-23-47
with flex it is centered
Screenshot from 2022-10-07 12-23-39

**Comment by yes-im-harsh** [comment]
@Nainish-Rai  I have updated all the CSS and also created the index.html in the root directory. I have done the changes. Kindly merge my PR. Let's help each other 😀. @Nainish-Rai

**Comment by Nainish-Rai** [comment]
@yes-im-harsh Thanks for efforts, It is quality contribution , Merged!

**Comment by yes-im-harsh** [comment]
> @yes-im-harsh Thanks for efforts, It is quality contribution , Merged!

Glad to help 😀. Looking forward to more contributions.

**Pull request merged**
