### PR TITLE
White theme added

### PR DESCRIPTION
**Pull request by heisdinesh**
white theme is added to the aesthetic-startpage using css

### CODE REVIEW

**Comment by Nainish-Rai** [comment]
@heisdinesh Please share a screenshot here

**Comment by heisdinesh** [comment]
white-theme

**Comment by Nainish-Rai** [comment]
@heisdinesh Looks good; Just reduce img width slightly. Check other theme

**Comment by heisdinesh** [comment]
sure will do the changes

**Comment by heisdinesh** [comment]
updated sir, now the image width is same as all other themes, thank you for the opportunity to learn.
white-heme-1

**Comment by Nainish-Rai** [comment]
@heisdinesh Looks nice, Thanks for Contribution

**Pull request merged**
