### PR TITLE
Added retrowave color scheme

### PR DESCRIPTION
**Pull request by Sidd2024**
Screenshot (24)

### CODE REVIEW

**Comment by Nainish-Rai** [comment]
@Sidd2024 This is awesome ; But i have changed the file-format so i suggest you to use the new format. 1.)Clone the latest repo,
put color changes in css starting (i have made variables) gif will be same 2) put this theme in new-themes folder

**Comment by Sidd2024** [comment]
@Nainish-Rai okay now?

**Comment by Nainish-Rai** [comment]
@Sidd2024 Change html css also there are minor changes. Compare yours with given in template-theme normal folder

**Comment by Sidd2024** [comment]
@Nainish-Rai sorry for the inconvinience, I've fixed it now!

**Comment by Nainish-Rai** [comment]
@Sidd2024 Great work, Thanks for contribution ; Merged

**Pull request merged**
