### PR TITLE
RGB gradient card

### PR DESCRIPTION
**Pull request by Morbius00**
Hacktober Badge
 Star Badge

## RGB Animation gradient card
Getting bored from normal colours and colour mesh why not add a spice of animation colour gradient  check out this folder for a spice touch up of animation using css

Screenshot 2022-10-05 155158

## Tech stacks used :
<a href="https://www.w3schools.com/css/" target="_blank" rel="noreferrer"> css3   <a href="https://www.w3.org/html/" target="_blank" rel="noreferrer"> html5 </a>

### CODE REVIEW

**Comment by Morbius00** [comment]
hope you like it and please dont forget to add the hactober fest label in it .
thanks 
regards,

**Comment by Nainish-Rai** [comment]
@Morbius00 color looks nice; Please fix search bar

**Comment by Morbius00** [comment]
> @Morbius00 color looks nice; Please fix search bar

ok i think its done

**Comment by Nainish-Rai** [comment]
@Morbius00 Please put this theme in new-theme folder

**Comment by Morbius00** [comment]
could you please check every think is ok or not

**Comment by Nainish-Rai** [comment]
@Morbius00 Looks Good, Thanks for contribution; Merged!

**Comment by Morbius00** [comment]
Thanks for the Merged @Nainish-Rai

**Pull request merged**
