### PR TITLE
added gray

### PR DESCRIPTION
**Pull request by shidoitsuka**
i added gray
i tried to find a perfect match for the font and ended up with this :
image
what do you think? feel free to make a comment about this and i'll update it 👍

### CODE REVIEW

**Comment by shidoitsuka** [comment]
check out #7 as well @Nainish-Rai

**Comment by Nainish-Rai** [comment]
@shidoitsuka Can you try changing link header color to that color on that nike logo

**Comment by shidoitsuka** [comment]
@Nainish-Rai on it!

**Comment by shidoitsuka** [comment]
pretty much like this :
image

i changed a little bit so it looks more contrast : 
image

tell me which one do you prefer

**Comment by Nainish-Rai** [comment]
@shidoitsuka 2nd one looks nice; But you changed the background position?

**Comment by shidoitsuka** [comment]
nope, probably scrolled by accident

**Comment by shidoitsuka** [comment]
commited ^

**Comment by Nainish-Rai** [comment]
@shidoitsuka  merged; Thanks for contributing !

**Pull request merged**
