### PR TITLE
Newtheme added

### PR DESCRIPTION
**Pull request by sumitbaroniya**

### CODE REVIEW

**Comment by Nainish-Rai** [comment]
@sumitbaroniya Please share a screenshot here

**Comment by sumitbaroniya** [comment]
@Nainish-Rai screenshot of a theme.

**Comment by sumitbaroniya** [comment]
bluish-purple-theme

**Comment by sumitbaroniya** [comment]
@Nainish-Rai screenshot of a theme.

**Comment by Nainish-Rai** [comment]
@sumitbaroniya https://i.pinimg.com/originals/35/af/db/35afdb6f6d1fffc467ffaebe7f618b8a.gif please replace gif with this one (link given) and then send a screenshot

**Comment by sumitbaroniya** [comment]
@Nainish-Rai new gif added and also updated a theme 
newtheme

**Comment by Nainish-Rai** [comment]
@sumitbaroniya Merged!!! This looks good; Thanks for contributing.

**Pull request merged**
