### PR TITLE
Adding New Themes Retro2077

### PR DESCRIPTION
**Pull request by anayatkhan1**
Hello @Nainish-Rai, I added New Theme File (Retro2077)✌️ , I hope you like it  please merge it 🙏

### CODE REVIEW

**Comment by Nainish-Rai** [comment]
@anayatkhan1 Share a screenshot here

**Comment by anayatkhan1** [comment]
> @anayatkhan1 Share a screenshot here

Screenshot 2022-10-13 212249

**Comment by Nainish-Rai** [comment]
@anayatkhan1 Gif isn't matching your theme; You can try this gif: https://i.pinimg.com/originals/d3/dd/be/d3ddbee2dd3f3e25a05d25954371da4e.gif

**Comment by anayatkhan1** [comment]
> @anayatkhan1 Gif isn't matching your theme; You can try this gif: https://i.pinimg.com/originals/d3/dd/be/d3ddbee2dd3f3e25a05d25954371da4e.gif

i fix it gif issue, check it
and thanks for sharing relatable gif it help me a alot

**Comment by Nainish-Rai** [comment]
@anayatkhan1 Looks nice, Thanks for contribution

**Pull request merged**
