### PR TITLE
Added gradient color - Red to Orange

### PR DESCRIPTION
**Pull request by vinayjain18**

### CODE REVIEW

**Comment by Nainish-Rai** [comment]
@vinayjain18 Please share a screenshot here

**Comment by vinayjain18** [comment]
gradient-pr

**Comment by Nainish-Rai** [comment]
@vinayjain18 Background looks amazing; But Please add a gif that matches the color theme; Also change the link heading color acc. to the theme.

**Comment by vinayjain18** [comment]
How will I get the same theme matching gif @Nainish-Rai ?

**Comment by vinayjain18** [comment]
gradient-color-changes
Is this perfect?

**Comment by Nainish-Rai** [comment]
@vinayjain18 I think you should find a gif with shades of red and orange color; You can find them on pinterest;

**Comment by vinayjain18** [comment]
3-gradient
How's this?

**Comment by Nainish-Rai** [comment]
https://i.pinimg.com/originals/ec/5a/e5/ec5ae5ab1d65424943003e00dc0b487b.gif

**Comment by vinayjain18** [comment]
Changed the gif with the one you have provided

**Comment by Nainish-Rai** [comment]
@vinayjain18 Looks good, Thanks for contributing; Merged!

**Pull request merged**
