### PR TITLE
updated light-pink theme in new-themes

### PR DESCRIPTION
**Pull request by Vagdevi007**

### CODE REVIEW

**Comment by Vagdevi007** [comment]
> @Vagdevi007 Please share a screenshot here.

Screenshot_20221010_221056.jpg -->

**Comment by Vagdevi007** [comment]
> @Vagdevi007 Please share a screenshot here.

Screenshot_20221010_221056.jpg -->

**Comment by Nainish-Rai** [comment]
@Vagdevi007 you should find a vertical gif/img matching your theme; You can find them on pinterest

**Comment by Vagdevi007** [comment]
Updated light-pink theme according to your suggestions.

**Pull request closed without merging**
