### PR TITLE
Added Aqua White Theme and also updated in Readme

### PR DESCRIPTION
**Pull request by dheeraj-singh-github**

### CODE REVIEW

**Comment by dheeraj-singh-github** [comment]
please accept my PR with the label hacktoberfest and hacktoberfest accepted

**Comment by Nainish-Rai** [comment]
@dheeraj-singh-github Please share a screenshot here

**Comment by dheeraj-singh-github** [comment]
Aqua White

**Comment by dheeraj-singh-github** [comment]
@Nainish-Rai is this theme ok ??

**Comment by Nainish-Rai** [comment]
@dheeraj-singh-github White and aquawhite is already there, I advice you to make a new unique theme, And use a vertical img.
Also read the guide to make new themes in readme

**Pull request closed without merging**
