### PR TITLE
Skin theme 

### PR DESCRIPTION
**Pull request by Chanchal14-creator**
I have added a new folder of new color theme of skin with  a new picture , please take a review and merge it if it seems appropriate to you.

### CODE REVIEW

**Comment by Nainish-Rai** [comment]
@Chanchal14-creator please share screenshot here

**Comment by sumitbaroniya** [comment]
Please assign me this issue

**Comment by Chanchal14-creator** [comment]
link for the image is given below plz check it out:
skin

**Comment by Nainish-Rai** [comment]
@Chanchal14-creator Merged! Thanks for contributing

**Pull request merged**
